# Generated by Django 5.1.4 on 2025-01-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image of the finished recipe",
                null=True,
                upload_to="recipe_images/",
            ),
        ),
    ]
