# Generated by Django 5.1.4 on 2025-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
